---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  namespace: default
data:
  #{if Octopus.Environment.Name == "Dev"}
  odEnvironmentName: "Dev"
  #{/if}
  #{if Octopus.Environment.Name == "Prod"}
  odEnvironmentName: "Prod"
  #{/if}
