---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
#{if Octopus.Environment.Name == "Dev"}
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
#{/if}
#{if Octopus.Environment.Name == "Prod"}
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
#{/if}
